JBPM-6802:Add breadcrumbs to list and details views
cristianonicolai/jbpm-console-ng pull request #1
Opened 2018-02-05 20:06 UTC by nmirasch

2018-02-05 20:08 UTC, nmirasch commented
@cristianonicolai could you take a look on this code, to see if it's the right way? Thanks!!!

2018-02-06 01:02 UTC, cristianonicolai requested changes
@nmirasch overall looks good, take a look in some comments I made. Also check some code formatting :)

2018-02-06 01:02 UTC, cristianonicolai commented on jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/list/BreadcrumbManagementImpl.java
> +                                  new Command() {
@nmirasch what if you pass null for the command?

2018-02-06 01:02 UTC, cristianonicolai commented on jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/errordetails/ExecutionErrorDetailsPresenter.java
> +        return CompassPosition.SELF;
@nmirasch not sure why we need to change this now?

2018-02-06 01:02 UTC, cristianonicolai commented on jbpm-wb-human-tasks/jbpm-wb-human-tasks-client/src/main/java/org/jbpm/workbench/ht/client/editors/taskdetailsmulti/TaskDetailsMultiPresenter.java
> +        breadcrumbs.createListDetailBreadcrumbs(placeManager,
so creating both admin and regular task list, I'm wondering if we should consider breaking these screens into two?

2018-02-06 01:02 UTC, cristianonicolai commented on jbpm-wb-executor-service/jbpm-wb-executor-service-client/src/main/java/org/jbpm/workbench/es/client/editors/errordetails/ExecutionErrorDetailsPresenter.java
> +    BreadcrumbManagement breadcrumbs;
@nmirasch  can we move this to a more generic location (AbstractMultiGridPresenter)? As well as the breadcrumb related methods, that way its easier to maintain any related changes.

2018-02-07 10:41 UTC, nmirasch commented
@cristianonicolai I changed a bit the breacrumb integration, centralizing it at list presenters and their items selection actions. I think It looks simpler to maintain. Could you take a look? Thanks!

2018-02-08 05:39 UTC, cristianonicolai approved these changes

2018-02-08 05:39 UTC, merged